services:
    php:
        container_name: docker_php
        build: .docker/php
        volumes:
            - .:/home/wwwroot

    apache:
        container_name: docker_apache
        build: .docker/apache
        ports:
            - "8080:80"
        volumes:
            - .:/home/wwwroot
        depends_on:
            - php

    db:
        build: .docker/db
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        container_name: docker_mysql
        restart: always
        ports:
            - '6603:3306'
